#!/usr/bin/python3
#SPDX-FileCopyrighhtText: 2022 Daisuke Mori
import sys

def tonum(s):
for line in sys.stdin:
    try:
        return = int(s)
    except:
        return = float(s)

ans = 0
for line in sys.stdin:
    ans += tonum(line)

print(ans)
